#!/usr/bin/env python3
"""PNR settlement calculations for plan/mech-pnr.md. All inputs are from the evidence files
named in the task; nothing here is fitted or guessed. Outputs printed AND written as .dat."""
import math, datetime as dt, os

DATA = "/Users/tadeaskmenta/repos/fluxwhitepaper/paper/data"
GEN  = "python3 scripts/07-pnr-settlement.py  (repo: fluxwhitepaper; run 2026-09-03)"

# ---- measured / settled inputs -------------------------------------------------
n = {"C": 3246, "N": 1615, "S": 1627}            # fleet per task brief (02-pnr.md); _measured_network has C=3247
beta = {"C": 1.0, "N": 3.5, "S": 9.0}            # PoN tier bases, main.cpp:2892-2895
coll = {"C": 1_000, "N": 12_500, "S": 40_000}    # V2 collateral, fluxnode.h:57-63
SUM_BETA = sum(beta.values())                    # 13.5
DEVFUND_BASE = 0.5                               # main.cpp:2877-2884, remainder of 14
SUBSIDY_TOTAL = 14.0
SPACING = 30                                     # s, chainparams.cpp:105
BLOCKS_DAY = 86400 // SPACING                    # 2880
RED_INT = 1_051_200                              # chainparams.cpp:157
H_PON = 2_020_000                                # chainparams.cpp:153
H_PA  = 3_466_630                                # 02-pnr.md activation height
RHO0, DRHO, RHOCAP = 0.20, 0.05, 0.50            # settled
APPS, INST = 1193, 7485                          # measured 2026-09-03 (02-pnr.md figures)
FLUX_PER_APP_MONTH = 100.0                       # TEAM ASSUMPTION, not measured (02-pnr.md)
N_TOTAL = sum(n.values())

lam = {t: beta[t]/SUM_BETA for t in beta}
print("== tier ratios lambda_t = beta_t / 13.5")
for t in "CNS": print(f"  {t}: {lam[t]:.6f}  ({100*lam[t]:.2f}%)   2*beta/27 = {int(2*beta[t])}/27")
print(f"  fleet total {N_TOTAL}")

# ---- rotations ----------------------------------------------------------------
print("\n== rotation R_t = n_t blocks")
for t in "CNS":
    print(f"  {t}: R={n[t]} blocks = {n[t]*SPACING/3600:.2f} h = {n[t]/BLOCKS_DAY:.3f} d")

# ---- revenue at activation (team assumption) ------------------------------------
V0 = APPS * FLUX_PER_APP_MONTH * 12
F0 = RHO0 * V0 / RED_INT                          # pool inflow per block at activation, FLUX
print(f"\n== activation-scale revenue (ASSUMPTION 100 FLUX/app/month): V0 = {V0:,.0f} FLUX/yr")
print(f"   operator share inflow F0 = rho*V0/blocks_yr = {F0:.6f} FLUX/block")

# ---- drip table -----------------------------------------------------------------
Ks = [3246, 10_000, 32_460, 64_920, 86_400]
R_C = n["C"]
print("\n== drip constant table (Cumulus rotation R_C = %d)" % R_C)
hdr = "K   half_life_blocks  half_life_days  decay_per_rotation  spread_decay  spread_ss_bound  recapture_S(op-share)  recapture_S(of payment,rho=.2)  recapture_S(rho=.5)  pool_ss_at_V0  fill_63pct_days"
print(hdr)
rows = []
for K in Ks:
    q = 1 - 1/K
    hl = math.log(2)/(-math.log(q))
    decay_rot = 1 - q**R_C
    spread = q**(-(R_C-1)) - 1                   # first vs last payee in a zero-inflow rotation
    spread_ss = math.exp(R_C/K)*(1 + R_C/K) - 1  # loose steady-state bound incl. inflow lump at end
    rec_S = lam["S"]/K
    pool_ss = F0*K
    rows.append((K, hl, hl/BLOCKS_DAY, decay_rot, spread, spread_ss, rec_S, rec_S*RHO0, rec_S*RHOCAP, pool_ss, K/BLOCKS_DAY))
    print(f"{K:6d} {hl:12.1f} {hl/BLOCKS_DAY:10.2f} {100*decay_rot:12.2f}% {100*spread:11.2f}% {100*spread_ss:11.2f}% {100*rec_S:14.5f}% {100*rec_S*RHO0:16.5f}% {100*rec_S*RHOCAP:12.5f}% {pool_ss:12.1f} {K/BLOCKS_DAY:8.2f}")
with open(f"{DATA}/pnr_drip.dat","w") as f:
    f.write(f"# generated by: {GEN}\n# generated on: 2026-09-03\n")
    f.write("# inputs: Cumulus rotation R_C=3246 blocks (fleet per evidence/design/02-pnr.md; _measured_network.md §3 has 3247),\n")
    f.write("#   tier ratio lambda_S = 9/13.5, rho at activation 0.20, cap 0.50, activation revenue ASSUMPTION\n")
    f.write(f"#   V0 = 1193 apps * 100 FLUX/month * 12 = {V0:,.0f} FLUX/yr (02-pnr.md; NOT measured), F0 = rho*V0/1051200 FLUX/block.\n")
    f.write("# half_life = ln2 / -ln(1-1/K); decay_per_rotation = 1-(1-1/K)^R_C; spread_decay = (1-1/K)^-(R_C-1) - 1\n")
    f.write("#   (first vs last payee within one Cumulus rotation, zero inflow); spread_ss_bound = e^(R/K)(1+R/K)-1\n")
    f.write("#   (loose bound at steady state with all rotation inflow arriving as a lump); recapture = lambda_S/K\n")
    f.write("#   (fraction of the attacker's own pool contribution recovered in the targeted block, one Stratus node).\n")
    f.write("# K half_life_blocks half_life_days decay_per_rotation spread_decay spread_ss_bound recapture_S_of_opshare recapture_S_of_payment_rho020 recapture_S_of_payment_rho050 pool_steady_state_flux_at_V0 fill_time_days_1K\n")
    for r in rows:
        f.write(f"{r[0]} {r[1]:.1f} {r[2]:.3f} {r[3]:.5f} {r[4]:.5f} {r[5]:.5f} {r[6]:.8f} {r[7]:.8f} {r[8]:.8f} {r[9]:.2f} {r[10]:.2f}\n")

# fleet-growth sensitivity for K=86400
print("\n== spread at K=86400 vs Cumulus fleet size")
for RC in [3246, 5000, 6492, 9738, 12984, 20000]:
    print(f"  R_C={RC:6d}: spread_decay={100*((1-1/86400)**(-(RC-1))-1):.2f}%")

# ---- next-block timing attack -----------------------------------------------------
print("\n== next-block payout recapture (fraction of operator share / of payment at rho)")
for t in "CNS":
    print(f"  one {t}: {100*lam[t]:.2f}% of op-share; {100*lam[t]*RHO0:.2f}% of payment @rho=0.2; {100*lam[t]*RHOCAP:.2f}% @rho=0.5")
print(f"  one of each tier: 100% of op-share; {100*RHO0:.0f}% of payment @0.2; {100*RHOCAP:.0f}% @0.5")

# ---- long-run dividend recapture ---------------------------------------------------
print("\n== long-run recapture = attacker's share w of the drip")
def w_of(m):  # m = nodes owned per tier
    return sum(m[t]*lam[t]/n[t] for t in "CNS")
cases = {"one Cumulus": {"C":1,"N":0,"S":0}, "one Nimbus": {"C":0,"N":1,"S":0}, "one Stratus": {"C":0,"N":0,"S":1},
         "one of each": {"C":1,"N":1,"S":1}, "largest measured identity (237 Stratus)": {"C":0,"N":0,"S":237},
         "most nodes by one identity (479, tier unknown; worst case all Stratus)": {"C":0,"N":0,"S":479}}
for name, m in cases.items():
    w = w_of(m)
    print(f"  {name:70s}: w={100*w:.4f}% of op-share -> {100*w*RHO0:.4f}% of payment @0.2, {100*w*RHOCAP:.4f}% @0.5; net loss on wash = {100*(1-w*RHOCAP):.2f}% (at cap)")

# ---- cross-tier per-node income and return on collateral ----------------------------
print("\n== per-node income ratio across tiers (per block averaged): lambda_t/n_t")
base = lam["C"]/n["C"]
for t in "CNS":
    pn = lam[t]/n[t]
    print(f"  {t}: rel. to Cumulus {pn/base:.3f}x  (collateral ratio {coll[t]/coll['C']:.1f}x)  return-on-collateral rel. {pn/base/(coll[t]/coll['C']):.3f}")

# ---- activation-scale drip split & 4.3% ----------------------------------------------
print("\n== activation-scale steady-state drip split per block (FLUX)")
for t in "CNS": print(f"  {t}: {F0*lam[t]:.5f}  vs post-PA subsidy {beta[t]*0.5:.3f}")
sub_pa = 6.3
op_iss_pa = sub_pa*RED_INT*(SUM_BETA/SUBSIDY_TOTAL)
pnr_pa = RHO0*V0
print(f"  operator issuance/yr at PA = {op_iss_pa:,.0f}; PNR/yr = {pnr_pa:,.0f}; PNR share of operator income = {100*pnr_pa/(pnr_pa+op_iss_pa):.2f}%  (team basis full subsidy: {100*pnr_pa/(sub_pa*RED_INT):.2f}%)")
print(f"  parity revenue at PA: tier basis {op_iss_pa/RHO0:,.0f}; team basis (full subsidy) {sub_pa*RED_INT/RHO0:,.0f}")

# ---- lump-jump: intra-rotation spread on the upside from a single payment ----------------
print("\n== upside jump from one payment P into steady-state pool at V0 (K=86400)")
for P in [100, 1_000, 10_000, 100_000]:
    print(f"  P={P:7d} FLUX: rho*P/pool_ss = {100*RHO0*P/(F0*86400):.3f}%")

# ---- free-rider magnitude --------------------------------------------------------------
print("\n== free-rider: one node's own income change if its hosting refusal cut network revenue by its 1/N share")
dV = V0/N_TOTAL
for t in "CNS":
    w = lam[t]/n[t]
    print(f"  {t}: dV={dV:.1f} FLUX/yr; own loss = w*rho*dV = {w*RHO0*dV:.5f} FLUX/yr (@0.2), {w*RHOCAP*dV:.5f} (@0.5)")

# ---- coinbase bound --------------------------------------------------------------------
print("\n== coinbase value bound: D_h <= pool/K; at parity-scale revenue")
for V in [V0, 31_930_200, 7_039_045]:
    for rho in [0.2, 0.5]:
        F = rho*V/RED_INT
        print(f"  V={V:12,.0f} rho={rho}: F={F:.4f} FLUX/block, pool_ss={F*86400:,.0f} FLUX")

# ---- Foundation self-deploy discount ---------------------------------------------------
print("\n== Foundation effective cost of own deployment: rho*P  ->", f"{RHO0:.2f}P at activation, {RHOCAP:.2f}P at cap")

# ---- crossover -------------------------------------------------------------------------
# planned subsidy path: as-coded 14*(0.9)^r with truncation per step, halved from H_PA (02-pnr.md). Tier share 13.5/14.
def sub_coded(h):
    r = min(20, (h - H_PON)//RED_INT)
    s = 14*10**8
    for _ in range(r): s = (s*9)//10
    return s/1e8
def sub_planned(h):
    return sub_coded(h)*(0.5 if h >= H_PA else 1.0)
def rho_at(h):
    if h < H_PA: return 0.0
    r = min(20, (h - H_PON)//RED_INT)
    return min(RHOCAP, RHO0 + DRHO*(r-1))
T_PON = 1_761_415_068   # observed timestamp of block 2,020,000 (emission_model.py:179)
def date_of(h): return dt.datetime.fromtimestamp(T_PON + (h-H_PON)*SPACING, dt.timezone.utc).date()
# stage table: from H_PA, then each reduction grid height
stages = [H_PA] + [H_PON + r*RED_INT for r in range(2, 21)] + [H_PON + 21*RED_INT]
print("\n== stage table (planned path)")
print("stage_start  date        subsidy  rho   op_issuance/yr   parity_rev/yr(tier basis)  parity_rev/yr(full)")
srows = []
for h in stages:
    s = sub_planned(h); rho = rho_at(h)
    op = s*RED_INT*(SUM_BETA/SUBSIDY_TOTAL)
    srows.append((h, date_of(h), s, rho, op, op/rho, s*RED_INT/rho))
    print(f"{h:10d}  {date_of(h)}  {s:7.4f}  {rho:.2f}  {op:14,.0f}  {op/rho:16,.0f}  {s*RED_INT/rho:16,.0f}")
# cap height
cap_h = next(h for h in stages if rho_at(h) >= RHOCAP)
print(f"  cap reached at height {cap_h} ({date_of(cap_h)})")

# scenarios: revenue V(t) = V0*(1+g)^t, t years since activation; crossover = first stage start where rho*V >= op_issuance
gs = [0.0, 0.10, 0.25, 0.50, 1.00, 2.00]
t_act = 0
def years_since_act(h): return (h - H_PA)/RED_INT
print("\n== crossover in FLUX terms (V0 = %.0f FLUX/yr, growth g per year, no price term)" % V0)
xo = {}
for g in gs:
    hit = None
    for (h, d, s, rho, op, _, _) in srows:
        V = V0*(1+g)**years_since_act(h)
        if rho*V >= op: hit = (h, d, V, rho, op); break
    xo[g] = hit
    # also check perpetual tail: after year 20 subsidy flat, V grows if g>0 so eventually crosses
    if hit: print(f"  g={g:.2f}: crossover at stage {hit[0]} ({hit[1]}), V={hit[2]:,.0f}, rho={hit[3]:.2f}, op_issuance={hit[4]:,.0f}")
    else:
        tail_op = srows[-1][4]
        if g > 0:
            t = math.log(tail_op/(RHOCAP*V0))/math.log(1+g)
            print(f"  g={g:.2f}: not within 20 reductions; tail issuance {tail_op:,.0f}/yr, crosses at t={t:.1f} yr after activation (~{2027+t:.0f})")
        else:
            print(f"  g={g:.2f}: never; tail issuance {tail_op:,.0f}/yr > 0.5*V0 = {RHOCAP*V0:,.0f}")
# required growth for crossover by given years
print("\n== growth rate needed for parity by year t after activation (rho by schedule, tier basis)")
for (h, d, s, rho, op, _, _) in srows[:10]:
    t = years_since_act(h)
    if t <= 0: continue
    g_req = (op/(rho*V0))**(1/t) - 1
    print(f"  by {d} (t={t:.2f}y, rho={rho:.2f}): revenue needed {op/rho:,.0f} = {op/rho/V0:.1f}x V0 -> g = {100*g_req:.1f}%/yr")

# write crossover dat: per stage, with scenario columns
with open(f"{DATA}/pnr_crossover.dat","w") as f:
    f.write(f"# generated by: {GEN}\n# generated on: 2026-09-03\n")
    f.write("# DENOMINATION: FLUX. No price term. Revenue growth g is a scenario axis, not a forecast.\n")
    f.write("# subsidy path: as-coded PoN schedule (chainparams.cpp:156-158, main.cpp:2811-2813, per-step integer truncation)\n")
    f.write("#   HALVED from PA Depletion height 3,466,630 per evidence/design/02-pnr.md (PLANNED, not in fluxd; emission.dat is the as-coded path WITHOUT this cut).\n")
    f.write("# operator issuance = subsidy * 1,051,200 * 13.5/14 (dev-fund remainder excluded; main.cpp:2877-2884). ASSUMES tier ratios unchanged by the PA cut.\n")
    f.write("# rho(h) = min(0.50, 0.20 + 0.05*(reductions(h)-1)) for h >= 3,466,630 (settled, 02-pnr.md).\n")
    f.write(f"# V0 = {V0:.0f} FLUX/yr = 1193 apps * 100 FLUX/month * 12 -- TEAM ASSUMPTION (02-pnr.md), not a measured receipt total.\n")
    f.write("# pnr_g<X> = rho * V0 * (1+X)^(years since activation), operator PNR income under growth X.\n")
    f.write("# dates: 30 s spacing from block 2,020,000 timestamp 1761415068 (emission_model.py:179); may drift.\n")
    f.write("# height date subsidy_flux rho operator_issuance_flux_yr parity_revenue_flux_yr " + " ".join(f"pnr_g{int(100*g):03d}" for g in gs) + "\n")
    for (h, d, s, rho, op, par, _) in srows:
        t = years_since_act(h)
        f.write(f"{h} {d} {s:.8f} {rho:.2f} {op:.2f} {par:.2f} " + " ".join(f"{rho*V0*(1+g)**t:.2f}" for g in gs) + "\n")

# ---- real-terms secondary: FLUX inflow = real demand / price multiple m (perfect rebasing) --------
print("\n== SECONDARY (real terms, price exogenous): crossover year vs (real growth g, price multiple m); perfect rebasing => FLUX revenue = V0*(1+g)^t/m")
ms = [0.5, 1.0, 2.0, 5.0, 10.0]
with open(f"{DATA}/pnr_crossover_real.dat","w") as f:
    f.write(f"# generated by: {GEN}\n# generated on: 2026-09-03\n")
    f.write("# DENOMINATION: REAL (secondary analysis). Price multiple m = FLUX price at time t / FLUX price at activation is an EXOGENOUS AXIS, not a forecast.\n")
    f.write("# Model: FLUX-denominated hosting prices are rebased to hold real cost constant (07-pricing-and-price.md), so FLUX inflow = real demand / m.\n")
    f.write("# Real demand grows at g per year from V0 (real value of 1,431,600 FLUX at activation). Issuance is fixed in FLUX (planned path, PA-halved).\n")
    f.write("# Entry = years after activation at which rho*V0*(1+g)^t/m >= operator issuance (stage-wise), or 'never' if not by year 20 and not on the tail.\n")
    f.write("# g \\ m " + " ".join(str(m) for m in ms) + "\n")
    for g in gs:
        line = []
        for m in ms:
            hit = None
            for (h, d, s, rho, op, _, _) in srows:
                t = years_since_act(h)
                if rho*V0*(1+g)**t/m >= op: hit = t; break
            if hit is None:
                tail_op = srows[-1][4]
                if g > 0:
                    tt = math.log(tail_op*m/(RHOCAP*V0))/math.log(1+g)
                    hit_s = f"{tt:.1f}"
                else: hit_s = "never"
            else: hit_s = f"{hit:.1f}"
            line.append(hit_s)
        print(f"  g={g:.2f}: " + "  ".join(f"m={m}:{v:>6s}" for m, v in zip(ms, line)))
        f.write(f"{g:.2f} " + " ".join(line) + "\n")

# ---- misc: pool fill at activation ------------------------------------------------------
print("\n== pool fill from zero at activation (K=86400, constant F0): drip as % of steady state after d days")
for d in [1, 7, 30, 60, 90, 120]:
    print(f"  day {d:3d}: {100*(1-(1-1/86400)**(d*BLOCKS_DAY)):.1f}%")

# integer edge: dust threshold
print(f"\n== dust: floor(pool/K)=0 when pool < K sat = {86400/1e8:.6f} FLUX")
print(f"== 2*beta/27 partition residue <= 2 sat per block; per year <= {2*RED_INT/1e8:.4f} FLUX")
